"""MCP-3D: Geometry-Aware Multi-Memory Test-Time Adaptation for 3D Point Cloud Recognition.

This file is the skeleton for the MCP-3D paper (AAAI 2027 / CVPR 2027).
Forks from runners/model_with_hierarchical_caches.py with the following extensions:

  C1) Compactness Memory using ICP-aligned Chamfer Distance (Section 4)
  C2) Compactness-Performance Correlation diagnosis hooks (Section 6)
  C3) 2x3 Memory Matrix (functional axis x representation axis, Section 7)
  C4) vMF MAP text anchor from DeepSeek paraphrases (Section 3)
  C5) Optional residual refinement (Section 9, MCP-3D++ extension, default OFF)

Implementation status (2026-05-08):
  [x] file structure and class signatures
  [ ] vMF MAP closed-form (W3)
  [ ] PCA + ICP + Chamfer (W4-W5)
  [ ] running stats (W4-W5)
  [ ] 2x3 memory matrix (W6)
  [ ] multi-source fusion (W6-W7)
  [ ] residual refinement MCP-3D++ (W19, CVPR phase)

Design references:
  /root/.windsurf/plans/mcp3d-logic-audit-and-revised-plan-f3c00d.md
  /root/autodl-tmp/MCP-Point-Cache/MCP3D_feasibility_and_proposal.md
"""
import json
import math
import operator
import os
import sys
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn.functional as F
import wandb

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils.utils import *  # noqa: F401,F403  (build_test_data_loader, get_logits, etc.)


# ============================================================================
# Section 2: Constants & default hyperparameters
# ----------------------------------------------------------------------------
# Per plan section 4.3 D3-D5 and audit gaps A6/A7
# ============================================================================
DEFAULT_KAPPA0 = 5.0          # vMF prior concentration (Gap D2: weak prior)
DEFAULT_OMEGA = 0.7           # ICP-CD vs feature distance fusion weight (Gap A7)
DEFAULT_ZSCORE_ALPHA = 0.1    # EMA rate for streaming z-score statistics (Gap A6)
DEFAULT_ICP_INIT_SAMPLES = 50 # samples used for global cold-start statistics (Gap A6)
DEFAULT_K_COMP = 3            # compactness memory shot capacity (Gap A3)
DEFAULT_ICP_MAX_ITER = 20     # ICP iterations (W2.5 P4 will tune)
DEFAULT_ICP_INLIER_RATIO = 0.7 # ICP success threshold (Gap E4)
DEFAULT_NUM_FPS = 256         # downsample for ICP/CD (computational budget)


# ============================================================================
# Section 3: vMF Text Anchor (closed-form MAP)
# ----------------------------------------------------------------------------
# Per plan section 3.3 (theory) and audit gap D2 (true selling point).
# Reference: Banerjee et al. "Clustering on the Unit Hypersphere using vMF"
# ============================================================================
@torch.no_grad()
def load_paraphrases_json(json_path: str) -> Dict[str, List[str]]:
    """Load DeepSeek paraphrases generated by generate_paraphrase.py.

    Returns dict mapping classname -> list of paraphrase strings.
    """
    if not os.path.exists(json_path):
        raise FileNotFoundError(
            f"Paraphrase JSON not found: {json_path}\n"
            f"  Run: python generate_paraphrase.py --datasets <dataset>"
        )
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)


@torch.no_grad()
def compute_vmf_anchor(
    paraphrase_features: torch.Tensor,  # (M, d), L2-normalized
    template_anchor: torch.Tensor,       # (d,), L2-normalized (multi-template ensemble)
    kappa0: float = DEFAULT_KAPPA0,
) -> torch.Tensor:
    """Closed-form MAP estimate of vMF mean direction with prior anchor.

    Posterior mode of vMF(z; mu, kappa) given prior vMF(mu; mu_0, kappa_0):
        a_c = normalize(kappa_hat * m_c + kappa_0 * z_bar)

    where m_c is the empirical mean direction of paraphrase embeddings,
    kappa_hat is estimated by Banerjee et al. method-of-moments,
    and z_bar = template_anchor (the prior).

    Args:
        paraphrase_features: (M, d) L2-normalized paraphrase embeddings
        template_anchor: (d,) prior anchor (multi-template ensemble), L2-normalized
        kappa0: prior concentration (higher -> trust template more)

    Returns:
        (d,) L2-normalized vMF MAP anchor.
    """
    M, d = paraphrase_features.shape

    # empirical mean direction
    sum_z = paraphrase_features.sum(dim=0)         # (d,)
    r_bar = sum_z.norm() / M                       # mean resultant length, scalar in [0, 1]
    m_c = sum_z / sum_z.norm()                     # (d,)

    # Banerjee et al. method-of-moments estimator for kappa_hat
    # kappa_hat = (r_bar * (d - r_bar^2)) / (1 - r_bar^2)
    eps = 1e-8
    kappa_hat = (r_bar * (d - r_bar ** 2)) / (1.0 - r_bar ** 2 + eps)
    kappa_hat = kappa_hat.clamp(min=eps)

    # MAP closed-form
    weighted = kappa_hat * m_c + kappa0 * template_anchor
    a_c = weighted / (weighted.norm() + eps)
    return a_c


@torch.no_grad()
def build_vmf_text_anchors(
    args,
    classnames: List[str],
    paraphrases: Dict[str, List[str]],
    template_anchor: torch.Tensor,  # (d, n_cls), per-class template ensemble
    clip_model,
    kappa0: float = DEFAULT_KAPPA0,
) -> torch.Tensor:
    """Build (d, n_cls) text anchors using vMF MAP for each class.

    For each class c:
        1. Encode all paraphrases of c via clip_model.encode_text -> (M, d)
        2. L2-normalize
        3. Compute vMF MAP anchor a_c with template_anchor[:, c] as prior
        4. Stack into (d, n_cls)

    Returns:
        clip_weights_vmf: (d, n_cls) replacing standard clip_weights from utils.clip_classifier
    """
    # TODO(W3): implement encoding loop, mirror utils.clip_classifier text encoding
    raise NotImplementedError("compute_vmf_anchor: implement W3 per plan §3.3")


# ============================================================================
# Section 4: ICP-CD Geometric Distance
# ----------------------------------------------------------------------------
# Per plan section 3.4 (method) and audit gaps A1-A5.
# Pipeline: PCA principal axis pre-align -> ICP fine -> Chamfer Distance.
# Fallback: if ICP fails (low inlier ratio), use feature distance only.
# ============================================================================
def pca_principal_axis_align(pc: torch.Tensor) -> torch.Tensor:
    """Align point cloud to its principal axes via PCA.

    Per Gap A4: ICP needs a reasonable initialization, otherwise it falls
    into local minima. Aligning principal axes provides a coarse alignment
    with O(N) cost.

    Args:
        pc: (B, N, 3) point cloud batch.
    Returns:
        pc_aligned: (B, N, 3) point cloud with axes sorted by variance.
    """
    # TODO(W4): implement
    #   1. center each pc to its centroid
    #   2. compute (3, 3) covariance per cloud
    #   3. eigendecompose, sort eigenvectors by eigenvalue desc
    #   4. apply rotation R (B, 3, 3) to bring principal axes to xyz
    raise NotImplementedError("pca_principal_axis_align: implement W4 per Gap A4")


def icp_then_chamfer(
    src: torch.Tensor,              # (B, N, 3) source point clouds
    tgt: torch.Tensor,              # (B, N, 3) target point clouds (same B)
    max_iter: int = DEFAULT_ICP_MAX_ITER,
    inlier_ratio_thresh: float = DEFAULT_ICP_INLIER_RATIO,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Compute ICP-aligned Chamfer Distance with success mask.

    Per plan section 3.4 lemma 1 (same-class -> CD ~ 0; different-class -> CD large).
    Per audit Gap A5: success threshold derived from W2.5 P4 statistics.

    Pipeline:
        1. PCA pre-align src to tgt principal axes (W4)
        2. pytorch3d.ops.iterative_closest_point  (rigid transformation)
        3. compute Chamfer Distance on registered pairs
        4. flag success based on inlier ratio >= inlier_ratio_thresh

    Args:
        src: (B, N, 3) candidate point clouds.
        tgt: (B, N, 3) reference (same-class anchor) point clouds.
    Returns:
        cd_scores: (B,) Chamfer distance per pair (lower = more similar)
        success_mask: (B,) bool, True if ICP succeeded
    """
    # TODO(W4-W5): implement
    #   from pytorch3d.ops import iterative_closest_point, knn_points
    #   from pytorch3d.loss import chamfer_distance
    raise NotImplementedError("icp_then_chamfer: implement W4-W5 per plan §3.4")


def icp_success_check(
    src_aligned: torch.Tensor,       # (B, N, 3)
    tgt: torch.Tensor,                # (B, N, 3)
    inlier_dist_thresh: float = 0.05,
) -> torch.Tensor:
    """Check if ICP registration succeeded based on inlier ratio.

    Per Gap E4: `success` = (fraction of NN distances < threshold) >= inlier_ratio.

    Args:
        src_aligned: ICP-aligned source.
        tgt: target.
        inlier_dist_thresh: NN distance threshold (calibrated from W2.5 P4).
    Returns:
        inlier_ratio: (B,) fraction of source points within threshold.
    """
    # TODO(W4): implement using pytorch3d.ops.knn_points
    raise NotImplementedError("icp_success_check: implement W4 per Gap E4")


# ============================================================================
# Section 5: Running Statistics (Streaming z-score)
# ----------------------------------------------------------------------------
# Per audit Gap A6: TTA is streaming with batch_size=1; we need running mean/std
# to z-score-normalize feature distance and ICP-CD distance before fusion.
# ============================================================================
class PerClassRunningStats:
    """Maintains exponentially-weighted running mean and std of a scalar per class.

    Used to z-score-normalize feature distance d_feat and geometric distance d_geo
    before linearly combining them with weight omega.
    """

    def __init__(
        self,
        num_classes: int,
        alpha: float = DEFAULT_ZSCORE_ALPHA,
        cold_start: int = DEFAULT_ICP_INIT_SAMPLES,
        device: str = "cuda",
    ):
        self.num_classes = num_classes
        self.alpha = alpha
        self.cold_start = cold_start
        self.device = device

        # per-class running statistics (cold-started with global pool)
        self.mu = torch.zeros(num_classes, device=device)
        self.var = torch.ones(num_classes, device=device)
        self.count = torch.zeros(num_classes, dtype=torch.long, device=device)

        # global pool for cold-start (used until per-class count reaches `cold_start`)
        self.global_mu = 0.0
        self.global_var = 1.0
        self.global_count = 0

    def update(self, class_idx: int, value: float) -> None:
        """Update running stats with a single observed value for class `class_idx`."""
        # global pool always updates
        self.global_count += 1
        delta = value - self.global_mu
        self.global_mu += delta / self.global_count
        self.global_var = (1 - self.alpha) * self.global_var + self.alpha * (delta ** 2)

        # per-class EMA update
        self.count[class_idx] += 1
        d = value - self.mu[class_idx].item()
        self.mu[class_idx] = (1 - self.alpha) * self.mu[class_idx] + self.alpha * value
        self.var[class_idx] = (1 - self.alpha) * self.var[class_idx] + self.alpha * (d ** 2)

    def normalize(self, class_idx: int, value: float) -> float:
        """Return z-scored value: (v - mu) / std."""
        eps = 1e-6
        if self.count[class_idx] < self.cold_start:
            mu = self.global_mu
            std = math.sqrt(self.global_var + eps)
        else:
            mu = self.mu[class_idx].item()
            std = math.sqrt(self.var[class_idx].item() + eps)
        return (value - mu) / std

    def state_dict(self) -> dict:
        return {
            "mu": self.mu.detach().cpu(),
            "var": self.var.detach().cpu(),
            "count": self.count.detach().cpu(),
            "global_mu": self.global_mu,
            "global_var": self.global_var,
            "global_count": self.global_count,
        }


# ============================================================================
# Section 6: Memory Cell (single cell of the 2x3 matrix)
# ----------------------------------------------------------------------------
# Per plan section 3.5 (system) and audit gaps C1-C2.
# A cell stores per-class lists of items. Item structure depends on cell type:
#   - confidence cells:  [feature_or_patch, loss]
#   - compactness cells: [feature_or_patch, loss, raw_pc, geom_score]
#   - boundary cells:    [feature_or_patch, loss, prob_map]
# ============================================================================
@dataclass
class CellConfig:
    """Configuration for a single memory cell.

    Attributes:
        name:           identifier such as 'global_conf', 'local_comp'
        representation: 'global' (whole-cloud feature) or 'local' (patch features)
        function:       'conf' | 'comp' | 'bnd'
        shot_capacity:  K shots per class
        alpha:          logit weight when fusing (Tip-Adapter style)
        beta:           sharpness in (-beta + beta * affinity).exp()
        enabled:        toggle for ablation A1 (leave-one-out)
    """
    name: str
    representation: str       # 'global' or 'local'
    function: str             # 'conf' | 'comp' | 'bnd'
    shot_capacity: int = 3
    alpha: float = 4.0
    beta: float = 3.0
    enabled: bool = True


class MemoryCell:
    """Generic memory cell that stores per-class items with a maximum shot capacity.

    Replacement update strategy:
      - confidence cells:    by lowest entropy/loss
      - compactness cells:   by smallest geometric score (after z-score normalize + omega-fuse)
      - boundary cells:      by lowest entropy within mid-entropy band
    """

    def __init__(self, config: CellConfig):
        self.cfg = config
        self.cache: Dict[int, List[list]] = {}

    def _sort_key(self, item: list) -> float:
        """Sort key for item replacement. Smaller is better (kept first)."""
        # item layout: [feat, ... , score]
        # for confidence/boundary -> score = loss (last numeric)
        # for compactness -> score = geom_combined_score (provided externally)
        if self.cfg.function == "comp":
            return item[-1]  # geom_combined_score
        return item[-2] if len(item) >= 3 else item[-1]

    def update(self, pred: int, item: list) -> None:
        """Update cell with a new item, keeping at most `shot_capacity` items per class."""
        if not self.cfg.enabled:
            return

        if pred in self.cache:
            if len(self.cache[pred]) < self.cfg.shot_capacity:
                self.cache[pred].append(item)
            else:
                # replace worst (last after sort) if new item is better
                worst_idx = -1
                if self._sort_key(item) < self._sort_key(self.cache[pred][worst_idx]):
                    self.cache[pred][worst_idx] = item
            self.cache[pred].sort(key=self._sort_key)
        else:
            self.cache[pred] = [item]

    def is_filled(self, num_classes: int) -> bool:
        """Whether all classes have reached shot_capacity."""
        if len(self.cache) < num_classes:
            return False
        return all(len(v) >= self.cfg.shot_capacity for v in self.cache.values())

    def num_items(self) -> int:
        return sum(len(v) for v in self.cache.values())


# ============================================================================
# Section 7: 2x3 Memory Matrix Manager
# ----------------------------------------------------------------------------
# Per plan section 3.5 (system architecture).
# Functional axis x Representation axis = 6 cells.
# Per audit Gap C1: A1 leave-one-out ablation will determine which 4-6 to keep.
# ============================================================================
class MCP3DMemoryMatrix:
    """Manages the 2x3 memory matrix for MCP-3D.

    Layout (functional x representation):

                    | global       | local
        ------------+--------------+--------------
        confidence  | global_conf  | local_conf
        compactness | global_comp  | local_comp
        boundary    | global_bnd   | local_bnd     # Gap C2: distinct from Point-Cache neg

    Each cell can be enabled/disabled via CellConfig.enabled for ablation A1.
    """

    CELL_NAMES = [
        "global_conf", "local_conf",
        "global_comp", "local_comp",
        "global_bnd", "local_bnd",
    ]

    def __init__(self, num_classes: int, cell_configs: Dict[str, CellConfig]):
        self.num_classes = num_classes
        # ensure all 6 names present (even if disabled)
        for name in self.CELL_NAMES:
            if name not in cell_configs:
                rep, func = name.split("_")
                cell_configs[name] = CellConfig(
                    name=name, representation=rep, function=func, enabled=False
                )
        self.cells: Dict[str, MemoryCell] = {
            name: MemoryCell(cfg) for name, cfg in cell_configs.items()
        }

    def get(self, name: str) -> MemoryCell:
        return self.cells[name]

    def all_filled(self) -> bool:
        return all(c.is_filled(self.num_classes) for c in self.cells.values() if c.cfg.enabled)

    def summary(self) -> str:
        lines = ["Memory matrix status:"]
        for name in self.CELL_NAMES:
            c = self.cells[name]
            lines.append(
                f"  {name:14s} | enabled={c.cfg.enabled} | classes={len(c.cache):3d} | items={c.num_items():4d}"
            )
        return "\n".join(lines)


# ============================================================================
# Section 8: Per-cell logits computation
# ----------------------------------------------------------------------------
# Extends Point-Cache's compute_cache_logits / compute_local_cache_logits with
# support for compactness cells (which use ICP-CD geometric score in addition).
# ============================================================================
@torch.no_grad()
def compute_cell_logits(
    cell: MemoryCell,
    query_feat: torch.Tensor,         # (1, d) for global, (n_patch, d) for local
    clip_weights: torch.Tensor,        # (d, n_cls)
    geom_distances: Optional[Dict[int, torch.Tensor]] = None,
    omega: float = DEFAULT_OMEGA,
    running_stats: Optional[PerClassRunningStats] = None,
) -> torch.Tensor:
    """Compute logits contribution from a single memory cell.

    For confidence/boundary cells: same as Point-Cache compute_cache_logits.
    For compactness cells: fuse feature affinity with ICP-CD geometric similarity:
        affinity_total = (1 - omega) * z(feature_aff) + omega * z(geom_aff)
    where z() is z-score normalization via running_stats and geom_aff = -d_geo.

    Args:
        cell: memory cell to use
        query_feat: query feature (already L2-normalized)
        clip_weights: (d, n_cls) for one-hot value lookup
        geom_distances: dict of class_idx -> (k_shot,) ICP-CD distances
                        (only for compactness cells)
        omega: fusion weight for geometric vs feature distance
        running_stats: per-class running statistics for z-score normalization

    Returns:
        cell_logits: (1, n_cls)
    """
    if not cell.cfg.enabled or len(cell.cache) == 0:
        return torch.zeros(1, clip_weights.size(1), device=clip_weights.device, dtype=clip_weights.dtype)

    # TODO(W6-W7): implement
    #   1. for global representation:
    #        cache_keys (d, n_cls*k) <- stack all item[0] across classes
    #        affinity (1, n_cls*k) = query_feat @ cache_keys
    #   2. for local representation:
    #        same as compute_local_cache_logits in Point-Cache
    #   3. for compactness function (Gap A1):
    #        also compute geom_affinity from geom_distances (z-scored)
    #        affinity = (1-omega)*z_feat + omega*(-z_geo)
    #   4. for boundary function (Gap C2):
    #        cache_values are prob_maps; apply mask_threshold like Point-Cache neg cache
    #   5. cache_logits = ((-1) * (beta - beta*affinity)).exp() @ cache_values
    raise NotImplementedError("compute_cell_logits: implement W6-W7 per plan §3.5")


# ============================================================================
# Section 9: Multi-source fusion (text + 6 cells, optional residual)
# ----------------------------------------------------------------------------
# Per plan section 3.6 (multi-source) and audit gap E3 (residual = optional).
# ============================================================================
@dataclass
class FusionWeights:
    """Adaptive fusion weights for multi-source logits.

    zeta_text: weight on text-anchor logits (zero-shot)
    zeta_cell: per-cell additive weights, alpha_i in plan
    zeta_residual: weight on residual refinement (default 0.3 per Gap E3)
    enable_residual: toggle for MCP-3D++ extension (default OFF for AAAI)
    """
    zeta_text: float = 1.0
    zeta_cell: Dict[str, float] = field(default_factory=dict)
    zeta_residual: float = 0.3
    enable_residual: bool = False


@torch.no_grad()
def fuse_multi_source_logits(
    text_logits: torch.Tensor,            # (1, n_cls)
    cell_logits_dict: Dict[str, torch.Tensor],  # name -> (1, n_cls)
    weights: FusionWeights,
    residual_logits: Optional[torch.Tensor] = None,
) -> torch.Tensor:
    """Combine text logits with all enabled cell logits.

    Final logits = zeta_text * text + sum_i zeta_cell[i] * cell_logits[i]
                   + zeta_residual * residual (if enable_residual)

    Notes:
      - boundary cells contribute negatively (cf. Point-Cache neg cache).
      - residual is OFF for AAAI version; CVPR may turn it on per A5 result.
    """
    final = weights.zeta_text * text_logits
    for name, cl in cell_logits_dict.items():
        if cl is None:
            continue
        sign = -1.0 if name.endswith("_bnd") else 1.0
        w = weights.zeta_cell.get(name, 1.0)
        final = final + sign * w * cl

    if weights.enable_residual and residual_logits is not None:
        final = final + weights.zeta_residual * residual_logits

    return final


# ============================================================================
# Section 10: Main TTA Loop
# ----------------------------------------------------------------------------
# Extends run_test_tda with:
#   - vMF text anchor (Section 3)
#   - 6-cell memory matrix (Section 6-7)
#   - ICP-CD compactness scoring (Section 4)
#   - z-score running statistics (Section 5)
#   - multi-source fusion (Section 9)
# ============================================================================
@torch.no_grad()
def run_mcp3d(
    args,
    test_loader,
    lm3d_model,
    clip_weights_text: torch.Tensor,        # (d, n_cls)
    matrix: MCP3DMemoryMatrix,
    fusion_weights: FusionWeights,
    running_stats: PerClassRunningStats,
):
    """Main TTA loop: streams test samples and fuses logits from text + 6 cells.

    Pseudocode (W6-W7 will flesh out the body):
        for sample in test_loader:
            1. Encode -> pc_feats, patch_centers, text_logits, loss, prob_map, pred
            2. For each enabled cell:
                a. (compactness only) compute ICP-CD geom_distances vs anchor pcs
                b. update cell with new item
                c. compute cell logits (using z-score normalize + omega fusion)
            3. Fuse: final_logits = text + sum(cells) - boundary_neg + residual?
            4. Report accuracy, log to wandb
    """
    accuracies = []
    num_classes = clip_weights_text.size(1)

    for i, batch in enumerate(test_loader):
        pc, target, _, rgb = batch
        feature = torch.cat([pc, rgb], dim=-1).half()

        pc_feats, patch_centers, text_logits, loss, prob_map, pred = get_logits(
            args, feature, lm3d_model, clip_weights_text
        )
        target = target.cuda()
        prop_entropy = get_entropy(loss, clip_weights_text)

        # ----- TODO(W6): per-cell update + logits computation -----
        # cell_logits_dict = {}
        # for name, cell in matrix.cells.items():
        #     if not cell.cfg.enabled: continue
        #     query = pc_feats if cell.cfg.representation == "global" else patch_centers
        #     # compactness-specific: compute geom score vs anchors of `pred` class
        #     geom_dist = None
        #     if cell.cfg.function == "comp":
        #         # 1. select anchor X_j per Gap A3: nearest in matrix.get('global_conf').cache[pred]
        #         # 2. compute ICP-CD via icp_then_chamfer
        #         # 3. update running_stats and z-score
        #         ...
        #     # update cell with current sample (only after some warmup)
        #     # cell.update(pred, [...])
        #     cell_logits_dict[name] = compute_cell_logits(
        #         cell, query, clip_weights_text, geom_dist, args.omega, running_stats
        #     )

        # ----- TODO(W7): fusion + accuracy -----
        # final_logits = fuse_multi_source_logits(
        #     text_logits, cell_logits_dict, fusion_weights, residual_logits=None
        # )
        # acc = cls_acc(final_logits, target)
        # accuracies.append(acc)

        # ----- placeholder: zero-shot only -----
        acc = cls_acc(text_logits, target)
        accuracies.append(acc)

        if args.wandb:
            wandb.log({"Averaged test accuracy": sum(accuracies) / len(accuracies)}, commit=True)

        if i % args.print_freq == 0:
            print(
                "[step {}] avg acc: {:.2f}  | matrix: {}".format(
                    i, sum(accuracies) / len(accuracies),
                    " ".join(f"{n}={c.num_items()}" for n, c in matrix.cells.items() if c.cfg.enabled)
                )
            )

    final_acc = sum(accuracies) / len(accuracies)
    print("---- *** Final *** MCP-3D test accuracy: {:.2f}. ----".format(final_acc))
    return final_acc


# ============================================================================
# Section 11: Entry point
# ----------------------------------------------------------------------------
# Mirrors model_with_hierarchical_caches.main() with MCP-3D-specific setup.
# Adds CLI flags via patching args (W3 will register these into utils.get_arguments).
# ============================================================================
def build_default_cell_configs() -> Dict[str, CellConfig]:
    """Default 2x3 cell configuration. Used by AAAI main experiments.

    Per audit Gap C1: A1 leave-one-out determines which to keep; for AAAI
    initial run we enable all 6 (will toggle in scripts/eval_mcp3d_*.sh).
    """
    return {
        "global_conf": CellConfig("global_conf", "global", "conf", shot_capacity=DEFAULT_K_COMP, enabled=True),
        "local_conf":  CellConfig("local_conf",  "local",  "conf", shot_capacity=DEFAULT_K_COMP, enabled=True),
        "global_comp": CellConfig("global_comp", "global", "comp", shot_capacity=DEFAULT_K_COMP, enabled=True),
        "local_comp":  CellConfig("local_comp",  "local",  "comp", shot_capacity=DEFAULT_K_COMP, enabled=True),
        "global_bnd":  CellConfig("global_bnd",  "global", "bnd",  shot_capacity=DEFAULT_K_COMP, enabled=True),
        "local_bnd":   CellConfig("local_bnd",   "local",  "bnd",  shot_capacity=DEFAULT_K_COMP, enabled=False),
        # local_bnd default OFF: Gap C2 says local boundary is conjectured weak; A1 will verify
    }


def main():
    args = get_arguments()
    set_random_seed(args.seed)

    # MCP-3D specific args (TODO W3: move to utils.get_arguments())
    if not hasattr(args, "omega"):
        args.omega = DEFAULT_OMEGA
    if not hasattr(args, "kappa0"):
        args.kappa0 = DEFAULT_KAPPA0
    if not hasattr(args, "use_vmf"):
        args.use_vmf = True
    if not hasattr(args, "paraphrase_json"):
        args.paraphrase_json = ""  # path to deepseek paraphrase JSON
    if not hasattr(args, "enable_residual"):
        args.enable_residual = False  # MCP-3D++ extension, OFF for AAAI

    config_path = args.config
    clip_model, lm3d_model = load_models(args)
    preprocess = None

    dataset_name = args.dataset
    print(f"Processing {dataset_name} dataset with MCP-3D.")
    cfg = get_config_file(args, config_path, dataset_name)
    print("\nDataset config:")
    print(cfg, "\n")

    test_loader, classnames, template = build_test_data_loader(args, dataset_name, args.data_root, preprocess)
    num_classes = len(classnames)

    # ----- text anchors: vMF MAP if paraphrases available, else fall back to template ensemble -----
    template_anchors = clip_classifier(args, classnames, template, clip_model)  # (d, n_cls)

    if args.use_vmf and args.paraphrase_json and os.path.exists(args.paraphrase_json):
        print(f"Loading paraphrases from {args.paraphrase_json}")
        paraphrases = load_paraphrases_json(args.paraphrase_json)
        # TODO(W3): wire build_vmf_text_anchors here once implemented
        clip_weights_text = template_anchors  # placeholder
        print("[INFO] vMF anchor not implemented yet (W3); using template ensemble.")
    else:
        clip_weights_text = template_anchors
        print("[INFO] using template ensemble text anchors (use_vmf=False or json missing)")

    # ----- 2x3 memory matrix -----
    cell_configs = build_default_cell_configs()
    matrix = MCP3DMemoryMatrix(num_classes=num_classes, cell_configs=cell_configs)
    print(matrix.summary())

    # ----- fusion weights (TODO W7: tune via A2 omega scan) -----
    fusion_weights = FusionWeights(
        zeta_text=1.0,
        zeta_cell={name: 1.0 for name in MCP3DMemoryMatrix.CELL_NAMES},
        zeta_residual=0.3,
        enable_residual=args.enable_residual,
    )

    # ----- running stats for z-score normalization -----
    running_stats = PerClassRunningStats(num_classes=num_classes)

    # ----- wandb logging -----
    if args.wandb:
        prefix = f"[mcp3d]/{args.lm3d}"
        if args.lm3d == "openshape":
            prefix += f"-{args.oshape_version}"
        elif args.lm3d == "ulip":
            prefix += f"-{args.ulip_version}"
        run_name = f"{prefix}/{dataset_name}/{args.cor_type if hasattr(args, 'cor_type') else 'clean'}"
        run = wandb.init(project="MCP-3D", config=cfg, name=run_name)

    # ----- run TTA -----
    acc = run_mcp3d(
        args=args,
        test_loader=test_loader,
        lm3d_model=lm3d_model,
        clip_weights_text=clip_weights_text,
        matrix=matrix,
        fusion_weights=fusion_weights,
        running_stats=running_stats,
    )

    if args.wandb:
        wandb.log({f"{dataset_name}": acc})
        run.finish()


if __name__ == "__main__":
    main()
